services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-app
    depends_on:
      - db
    volumes:
      - output:/var/www/html/output

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-apache
    depends_on:
      - app
    environment:
      LDAP_ENABLED: "false"

  db:
    image: mariadb:10.6
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: offline-circ
      MYSQL_USER: offline-circ
      MYSQL_PASSWORD: offline-circ
    volumes:
      - db:/var/lib/mysql
      - ./docker/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db: {}
  output: {}
